name: Test gradle triggers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch name
        id: get_branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Print branch name
        run: echo "Current branch is ${{ env.branch_name }}"