name: Test gradle triggers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: !contains(github.event.head_commit.message, '(#')

    steps:
      - name: Test
        run: |
          echo "test"
          echo ${{github.event.pull_request.merged}}
          echo ${{github.event.pull_request.merged != true}}