name: Test gradle triggers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        uses: cli/cli@latest

      - name: Get merged PR information
        id: pr_info
        run: |
          PR_JSON=$(gh pr list --state merged --search "$(git rev-parse HEAD)" --json headRefName,number --limit 1)
           echo "Source branch: $(echo $PR_JSON | jq -r '.[0].headRefName')"