name: Test gradle triggers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get merged PR information
        id: pr_info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_json=$(gh pr list --state merged --search "$(git rev-parse HEAD)" --json headRefName,number --limit 1)
          echo $pr_json
          pr_branch=$(echo $PR_JSON | jq -r '.[0].headRefName')
          if [ -n $pr_branch]; then 
            echo $pr_branch
          else
            echo "No branch"
          fi